// savers.js — the complete 37 in-tree ASCII scenes manifest.
// Showcase and matrix are rendered from this table.
const SAVERS = [
  // ==========================================
  // 37 IN-TREE PUNCHY ASCII SCENES (CORE v4.x)
  // ==========================================
  { num: "01", id: "fireworks", name: "FIREWORKS", sub: "Aerial Pyrotechnic Bursts",
    desc: "Rockets firing upward with luminous tracer tails, detonating into vibrant radial particle bursts with gravitic cascade and sparkle decay.",
    frame: "60–144 FPS", cpu: "0.09%", math: "Ballistic Trajectories",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "particles", "pyrotechnic", "ballistic", "fireworks.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/fireworks.rs",
    sourceLabel: "[ SOURCE: fireworks.rs ↗ ]",
    video: "assets/videos/bursts.mp4" },

  { num: "02", id: "matrix", name: "MATRIX", sub: "Digital Rain Cascade",
    desc: "Iconic cascading streams of descending green characters with glowing phosphor leading heads, fading tails, and dynamic mutation.",
    frame: "60–144 FPS", cpu: "0.08%", math: "Phosphor Stream Physics",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "crypto", "matrix", "phosphor", "cascade", "matrix.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/matrix.rs",
    sourceLabel: "[ SOURCE: matrix.rs ↗ ]",
    video: "assets/videos/glyphs.mp4" },

  { num: "03", id: "synthgrid", name: "SYNTHGRID", sub: "Retrowave Vector Horizon",
    desc: "3D perspective vector wireframe grid sweeping toward the camera under a glowing neon horizon with undulating topographic terrain.",
    frame: "60–144 FPS", cpu: "0.09%", math: "Perspective Homography",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "vector", "synthwave", "retrowave", "3d", "synthgrid.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/synthgrid.rs",
    sourceLabel: "[ SOURCE: synthgrid.rs ↗ ]",
    video: "assets/videos/ascii.mp4" },

  { num: "04", id: "blackhole", name: "BLACK HOLE", sub: "Gravitational Event Horizon",
    desc: "Relativistic accretion disk spinning around a gravitational singularity, lensing and consuming characters in an orbital vortex.",
    frame: "60–144 FPS", cpu: "0.09%", math: "Schwarzschild Geodesics",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "motion", "gravity", "orbital", "relativity", "blackhole.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/blackhole.rs",
    sourceLabel: "[ SOURCE: blackhole.rs ↗ ]",
    video: "assets/videos/cosmos.mp4" },

  { num: "05", id: "thunderstorm", name: "THUNDERSTORM", sub: "Dielectric Lightning Discharge",
    desc: "Violent electrical storm simulation with branching dielectric lightning discharges, flash-bulb screen lighting, and driving rain.",
    frame: "60–144 FPS", cpu: "0.09%", math: "Dielectric Breakdown Trees",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "fluid", "plasma", "lightning", "weather", "thunderstorm.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/thunderstorm.rs",
    sourceLabel: "[ SOURCE: thunderstorm.rs ↗ ]",
    video: "assets/videos/storm.mp4" },

  { num: "06", id: "beams", name: "BEAMS", sub: "Vector Acceleration",
    desc: "Crossing searchlight vector cones sweeping a high-contrast field. Calculates real-time ray intersections with phosphor persistence decay.",
    frame: "60–144 FPS", cpu: "0.08%", math: "Vector Grid / Ray Tracing",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "vector", "optics", "raytrace", "phosphor", "beams.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/beams.rs",
    sourceLabel: "[ SOURCE: beams.rs ↗ ]",
    video: "assets/videos/beams.mp4" },

  { num: "07", id: "rain", name: "RAIN", sub: "Atmospheric Downpour",
    desc: "Diagonal driving rain streaks across the screen with wind shear drift, splash particle impacts on bottom boundaries, and puddle ripples.",
    frame: "60–144 FPS", cpu: "0.08%", math: "Wind Shear Kinematics",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "fluid", "weather", "downpour", "kinetics", "rain.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/rain.rs",
    sourceLabel: "[ SOURCE: rain.rs ↗ ]",
    video: "assets/videos/ripple.mp4" },

  { num: "08", id: "waves", name: "WAVES", sub: "Harmonic Wave Mechanics",
    desc: "Continuous 2D wave equations generating sinusoidal ripples, harmonic standing nodes, and surface refraction across character cells.",
    frame: "60–144 FPS", cpu: "0.07%", math: "2D Wave Mechanics",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "fluid", "motion", "wave", "harmonics", "waves.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/waves.rs",
    sourceLabel: "[ SOURCE: waves.rs ↗ ]",
    video: "assets/videos/ripple.mp4" },

  { num: "09", id: "binarypath", name: "BINARY PATH", sub: "Circuit Bus Interconnects",
    desc: "Microscopic PCB trace routing tracing binary ones and zeros along orthogonal bus interconnects with sub-pixel snap.",
    frame: "60–144 FPS", cpu: "0.07%", math: "Manhattan Circuit Routing",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "crypto", "circuit", "bus", "pcb", "binarypath.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/binarypath.rs",
    sourceLabel: "[ SOURCE: binarypath.rs ↗ ]",
    video: "assets/videos/ascii.mp4" },

  { num: "10", id: "bouncyballs", name: "BOUNCY BALLS", sub: "Elastic Particle Collision",
    desc: "Newtonian physics simulation of bounding spherical particle bodies with elastic restitution, kinetic momentum transfer, and gravity.",
    frame: "60–144 FPS", cpu: "0.08%", math: "Elastic Collision Physics",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "particles", "motion", "physics", "elastic", "bouncyballs.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/bouncyballs.rs",
    sourceLabel: "[ SOURCE: bouncyballs.rs ↗ ]",
    video: "assets/videos/ascii.mp4" },

  { num: "11", id: "bubbles", name: "BUBBLES", sub: "Buoyant Fluid Dynamics",
    desc: "Buoyant liquid spheres rising from the deep, wobbling with harmonic surface tension and popping into mist upon reaching the surface.",
    frame: "60–144 FPS", cpu: "0.07%", math: "Buoyancy / Surface Tension",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "particles", "fluid", "buoyancy", "spheres", "bubbles.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/bubbles.rs",
    sourceLabel: "[ SOURCE: bubbles.rs ↗ ]",
    video: "assets/videos/ascii.mp4" },

  { num: "12", id: "burn", name: "BURN", sub: "Pyrotechnic Combustion Front",
    desc: "Combustion wave front advancing across glyphs, leaving glowing cinder trails, rising buoyant smoke, and ash dispersal.",
    frame: "60–144 FPS", cpu: "0.09%", math: "Combustion Reaction Diffusion",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "fluid", "fire", "plasma", "combustion", "burn.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/burn.rs",
    sourceLabel: "[ SOURCE: burn.rs ↗ ]",
    video: "assets/videos/hearth.mp4" },

  { num: "13", id: "colorshift", name: "COLOR SHIFT", sub: "HSV Chromatic Oscillation",
    desc: "Continuous radial HSV chromatic spectrum oscillation sweeping through terminal cells with smooth sinusoidal phase modulation.",
    frame: "60–144 FPS", cpu: "0.06%", math: "Trigonometric Hue Gradient",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "vector", "optics", "chroma", "hsv", "colorshift.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/colorshift.rs",
    sourceLabel: "[ SOURCE: colorshift.rs ↗ ]",
    video: "assets/videos/aurora.mp4" },

  { num: "14", id: "crumble", name: "CRUMBLE", sub: "Seismic Structural Failure",
    desc: "Structural stress fractures propagating through character glyphs, collapsing the banner into tumbling debris under gravity.",
    frame: "60–144 FPS", cpu: "0.08%", math: "Fracture Dynamics",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "particles", "motion", "collapse", "debris", "crumble.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/crumble.rs",
    sourceLabel: "[ SOURCE: crumble.rs ↗ ]",
    video: "assets/videos/ascii.mp4" },

  { num: "15", id: "decrypt", name: "DECRYPT", sub: "Cryptographic Cipher Solver",
    desc: "High-entropy cyphertext stream resolving character by character into target wordmark as decryption key bits are found.",
    frame: "60–144 FPS", cpu: "0.06%", math: "Entropy Reduction / PRNG",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "crypto", "cipher", "entropy", "prng", "decrypt.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/decrypt.rs",
    sourceLabel: "[ SOURCE: decrypt.rs ↗ ]",
    video: "assets/videos/glyphs.mp4" },

  { num: "16", id: "errorcorrect", name: "ERROR CORRECT", sub: "Hamming Parity Scrubbing",
    desc: "Simulates memory parity corruption, ECC syndrome calculation, and automated bit-flip scrub passes across the terminal display.",
    frame: "60–144 FPS", cpu: "0.07%", math: "Hamming ECC Algorithm",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "crypto", "memory", "hamming", "ecc", "errorcorrect.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/errorcorrect.rs",
    sourceLabel: "[ SOURCE: errorcorrect.rs ↗ ]",
    video: "assets/videos/ascii.mp4" },

  { num: "17", id: "expand", name: "EXPAND", sub: "Radial Kinetic Blast",
    desc: "Centrifugal kinetic explosion blasting characters from the center out toward display borders before snapping back with elastic dampening.",
    frame: "60–144 FPS", cpu: "0.08%", math: "Radial Impulse Vectors",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "motion", "shockwave", "radial", "impulse", "expand.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/expand.rs",
    sourceLabel: "[ SOURCE: expand.rs ↗ ]",
    video: "assets/videos/bursts.mp4" },

  { num: "18", id: "highlight", name: "HIGHLIGHT", sub: "Linear Optical Scanner",
    desc: "Ultra-bright collimated optical scan bar sweeping horizontally across text glyphs, creating high-phosphor persistence blooms.",
    frame: "60–144 FPS", cpu: "0.06%", math: "Gaussian Optical Sweep",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "vector", "optics", "specular", "scan", "highlight.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/highlight.rs",
    sourceLabel: "[ SOURCE: highlight.rs ↗ ]",
    video: "assets/videos/beams.mp4" },

  { num: "19", id: "laseretch", name: "LASER ETCH", sub: "Coherent Photon Beam",
    desc: "Industrial high-power vector laser etching glyph contours with incandescent spark splatter and burnished edge glow.",
    frame: "60–144 FPS", cpu: "0.08%", math: "CNC Vector Pathing",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "vector", "optics", "laser", "photon", "laseretch.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/laseretch.rs",
    sourceLabel: "[ SOURCE: laseretch.rs ↗ ]",
    video: "assets/videos/beams.mp4" },

  { num: "20", id: "middleout", name: "MIDDLE OUT", sub: "Bilateral Expansion Compression",
    desc: "Bilateral compression architecture unfolding and rendering glyphs symmetrically outward from the center column to display edges.",
    frame: "60–144 FPS", cpu: "0.07%", math: "Bilateral Column Sweep",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "crypto", "compression", "bilateral", "middleout.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/middleout.rs",
    sourceLabel: "[ SOURCE: middleout.rs ↗ ]",
    video: "assets/videos/ascii.mp4" },

  { num: "21", id: "orbittingvolley", name: "ORBITTING VOLLEY", sub: "Dual Satellite Cannons",
    desc: "Pair of counter-orbiting particle turrets firing kinetic crossfire barrages into a central gravitational singularity.",
    frame: "60–144 FPS", cpu: "0.09%", math: "Orbital Ballistics",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "motion", "orbital", "ballistics", "gravity", "orbittingvolley.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/orbittingvolley.rs",
    sourceLabel: "[ SOURCE: orbittingvolley.rs ↗ ]",
    video: "assets/videos/chaos.mp4" },

  { num: "22", id: "overflow", name: "OVERFLOW", sub: "Hexadecimal Heap Cascade",
    desc: "Simulated memory buffer overrun cascading address offsets, raw hexadecimal dumps, and pointer corruption down the terminal rows.",
    frame: "60–144 FPS", cpu: "0.07%", math: "Heap Dump Traversal",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "crypto", "memory", "buffer", "heap", "overflow.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/overflow.rs",
    sourceLabel: "[ SOURCE: overflow.rs ↗ ]",
    video: "assets/videos/ascii.mp4" },

  { num: "23", id: "pour", name: "POUR", sub: "Laminar Fluid Stream",
    desc: "Viscous fluid stream pouring from the terminal ceiling, splashing, spreading, and pooling along floor boundaries.",
    frame: "60–144 FPS", cpu: "0.08%", math: "Viscous Liquid Flow",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "fluid", "cascade", "liquid", "viscous", "pour.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/pour.rs",
    sourceLabel: "[ SOURCE: pour.rs ↗ ]",
    video: "assets/videos/ascii.mp4" },

  { num: "24", id: "print", name: "PRINT", sub: "Dot-Matrix Carriage Impact",
    desc: "High-speed 24-pin impact dot-matrix print carriage sweeping across the platen line by line with mechanical carriage returns.",
    frame: "60–144 FPS", cpu: "0.06%", math: "Mechanical Stepper Emulation",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "crypto", "retro", "dotmatrix", "stepper", "print_effect.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/print_effect.rs",
    sourceLabel: "[ SOURCE: print_effect.rs ↗ ]",
    video: "assets/videos/ascii.mp4" },

  { num: "25", id: "random_sequence", name: "RANDOM SEQUENCE", sub: "Stochastic Character Annealing",
    desc: "Stochastic randomized character shuffle annealing into target text as entropy temperature drops to zero.",
    frame: "60–144 FPS", cpu: "0.07%", math: "Simulated Annealing",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "crypto", "stochastic", "annealing", "entropy", "random_sequence.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/random_sequence.rs",
    sourceLabel: "[ SOURCE: random_sequence.rs ↗ ]",
    video: "assets/videos/glyphs.mp4" },

  { num: "26", id: "rings", name: "RINGS", sub: "Harmonic Acoustic Resonators",
    desc: "Expanding concentric shockwave rings radiating from multiple resonance nodes, producing acoustic interference patterns.",
    frame: "60–144 FPS", cpu: "0.08%", math: "Bessel Ring Propagation",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "vector", "optics", "resonance", "bessel", "rings.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/rings.rs",
    sourceLabel: "[ SOURCE: rings.rs ↗ ]",
    video: "assets/videos/ripple.mp4" },

  { num: "27", id: "scattered", name: "SCATTERED", sub: "Brownian Particle Snapping",
    desc: "Chaotic Brownian particle drift dispersing glyphs across the field before magnetic coherence pulls every cell into position.",
    frame: "60–144 FPS", cpu: "0.08%", math: "Magnetic Dipole Convergence",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "particles", "coherence", "brownian", "scattered.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/scattered.rs",
    sourceLabel: "[ SOURCE: scattered.rs ↗ ]",
    video: "assets/videos/chaos.mp4" },

  { num: "28", id: "slice", name: "SLICE", sub: "Horizontal Shear Tectonic",
    desc: "Alternating horizontal shear planes slicing across text rows in opposing directions with crisp sub-pixel alignment snap.",
    frame: "60–144 FPS", cpu: "0.06%", math: "Tectonic Shear Matrix",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "motion", "kinetic", "shear", "tectonic", "slice.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/slice.rs",
    sourceLabel: "[ SOURCE: slice.rs ↗ ]",
    video: "assets/videos/ascii.mp4" },

  { num: "29", id: "slide", name: "SLIDE", sub: "Inertial Lateral Easing",
    desc: "High-velocity lateral entrance sliding characters from offscreen with tuned cubic easing and spring-damper settling.",
    frame: "60–144 FPS", cpu: "0.06%", math: "Cubic Easing-Out Physics",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "motion", "slide", "kinetic", "easing", "slide.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/slide.rs",
    sourceLabel: "[ SOURCE: slide.rs ↗ ]",
    video: "assets/videos/ascii.mp4" },

  { num: "30", id: "smoke", name: "SMOKE", sub: "Navier-Stokes Convection",
    desc: "Turbulent fluid smoke billows rising and curling through the character field, dissipating into atmospheric ambient haze.",
    frame: "60–144 FPS", cpu: "0.09%", math: "Eulerian Fluid Grid",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "particles", "fluid", "gas", "convection", "smoke.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/smoke.rs",
    sourceLabel: "[ SOURCE: smoke.rs ↗ ]",
    video: "assets/videos/hearth.mp4" },

  { num: "31", id: "spotlights", name: "SPOTLIGHTS", sub: "Theatrical Dual Cones",
    desc: "Dual roving theatrical spotlight cones sweeping over a darkened field, revealing illuminated glyphs wherever beams intersect.",
    frame: "60–144 FPS", cpu: "0.08%", math: "Conical Ray Cast",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "vector", "optics", "lighting", "searchlight", "spotlights.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/spotlights.rs",
    sourceLabel: "[ SOURCE: spotlights.rs ↗ ]",
    video: "assets/videos/beams.mp4" },

  { num: "32", id: "spray", name: "SPRAY", sub: "Pneumatic Aerosol Stencil",
    desc: "High-velocity aerosol droplet spray nozzle painting characters onto the terminal platen with stochastic mist splatter.",
    frame: "60–144 FPS", cpu: "0.08%", math: "Pneumatic Droplet Distribution",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "particles", "fluid", "aerosol", "spray.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/spray.rs",
    sourceLabel: "[ SOURCE: spray.rs ↗ ]",
    video: "assets/videos/ascii.mp4" },

  { num: "33", id: "swarm", name: "SWARM", sub: "Reynolds Flocking Boids",
    desc: "Multi-agent autonomous boid flock calculating separation, alignment, and cohesion steering vectors around text boundaries.",
    frame: "60–144 FPS", cpu: "0.09%", math: "Emergent Boid Flocking",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "particles", "boids", "flocking", "agents", "swarm.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/swarm.rs",
    sourceLabel: "[ SOURCE: swarm.rs ↗ ]",
    video: "assets/videos/gnats.mp4" },

  { num: "34", id: "sweep", name: "SWEEP", sub: "Polar Azimuthal Radar",
    desc: "Rotating azimuthal radar sweep arm refreshing phosphor luminosity across cells with continuous exponential decay.",
    frame: "60–144 FPS", cpu: "0.07%", math: "Polar Coordinate Beam",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "motion", "radar", "angular", "azimuthal", "sweep.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/sweep.rs",
    sourceLabel: "[ SOURCE: sweep.rs ↗ ]",
    video: "assets/videos/radar.mp4" },

  { num: "35", id: "unstable", name: "UNSTABLE", sub: "Quantum State Fluctuations",
    desc: "Characters vibrating with quantum uncertainty, sporadic chromatic aberration, phase shifts, and high-frequency jitter.",
    frame: "60–144 FPS", cpu: "0.07%", math: "Stochastic Quantum Jitter",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "crypto", "quantum", "jitter", "stochastic", "unstable.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/unstable.rs",
    sourceLabel: "[ SOURCE: unstable.rs ↗ ]",
    video: "assets/videos/ascii.mp4" },

  { num: "36", id: "vhstape", name: "VHS TAPE", sub: "Magnetic Tracking Drift",
    desc: "Analog CRT scanlines, horizontal tape tracking sync errors, color bleed, and authentic magnetic tape playback noise.",
    frame: "60–144 FPS", cpu: "0.08%", math: "Analog Scanline Simulation",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "crypto", "analog", "crt", "scanlines", "vhstape.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/vhstape.rs",
    sourceLabel: "[ SOURCE: vhstape.rs ↗ ]",
    video: "assets/videos/ascii.mp4" },

  { num: "37", id: "wipe", name: "WIPE", sub: "Sub-pixel Linear Dissolve",
    desc: "Clean directional transition wiping across the screen with sharp phosphor boundary and sub-pixel glyph replacement.",
    frame: "60–144 FPS", cpu: "0.06%", math: "Linear Spatial Mask",
    badge: "IN-TREE SCENE",
    tags: ["in-tree", "ascii", "motion", "transition", "dissolve", "linear", "wipe.rs"],
    sourceUrl: "https://github.com/idlescreen/idlescreen/blob/master/crates/idlescreen/src/ascii/scenes/wipe.rs",
    sourceLabel: "[ SOURCE: wipe.rs ↗ ]",
    video: "assets/videos/ascii.mp4" },
];
