// savers.js — the plugin manifest. Panels are generated from this table.
const SAVERS = [
  { num: "01", id: "beams", name: "BEAMS", sub: "Vector Acceleration",
    desc: "Crossing vector beams across a high-contrast field. Calculates real-time ray intersections with phosphor persistence decay.",
    frame: "60 FPS", cpu: "0.15%", math: "Vector Grid",
    tags: ["wayland", "vector", "phosphor"], live: "assets/wasm/beams.wasm" },
  { num: "02", id: "cosmos", name: "COSMOS", sub: "Celestial Kinematics",
    desc: "Starfield and nebula-style deep-space celestial kinematics. Simulates gravitational velocity vectors and star parallax across depth planes.",
    frame: "60 FPS", cpu: "0.22%", math: "N-Body Gravitation",
    tags: ["wayland", "gravity", "3d"] },
  { num: "03", id: "bursts", name: "BURSTS", sub: "Shockwave Dynamics",
    desc: "High-velocity explosive shockwave patterns, expanding rings, and kinetic particle dissipation with zero memory accumulation.",
    frame: "60 FPS", cpu: "0.18%", math: "Kinetic Shockwave",
    tags: ["wayland", "kinetic", "particles"] },
  { num: "04", id: "storm", name: "STORM", sub: "Atmospheric Plasma",
    desc: "Dense atmospheric particulate clouds with stochastic dielectric breakdown arcs and lightning flash illumination.",
    frame: "60 FPS", cpu: "0.25%", math: "Dielectric Arcs",
    tags: ["wayland", "plasma", "stochastic"] },
  { num: "05", id: "chaos", name: "CHAOS", sub: "Strange Attractors",
    desc: "Strange-attractor non-linear dynamical systems. Integrates three-dimensional differential equations into phosphor phase-space trajectories.",
    frame: "60 FPS", cpu: "0.14%", math: "Lorenz / Attractor",
    tags: ["wayland", "chaos", "phase"] },
  { num: "06", id: "hearth", name: "HEARTH", sub: "Thermodynamics",
    desc: "Warm ember and fire-like ambient cellular convection. Simulates heat dissipation, buoyant updraft, and cooling cinder particles.",
    frame: "60 FPS", cpu: "0.19%", math: "Thermal Convection",
    tags: ["wayland", "thermal", "cellular"] },
  { num: "07", id: "ripple", name: "RIPPLE", sub: "Wave Equations",
    desc: "2D discrete wave equation solver. Generates interference ripples, harmonic standing waves, and surface refraction across the display.",
    frame: "60 FPS", cpu: "0.17%", math: "2D Wave Mechanics",
    tags: ["wayland", "wave", "interference"] },
  { num: "08", id: "radar", name: "RADAR", sub: "Polar Telemetry",
    desc: "360-degree polar coordinate radar sweep with simulated phosphor persistence, range rings, and synthetic target Doppler blips.",
    frame: "60 FPS", cpu: "0.12%", math: "Polar Coordinate Sweep",
    tags: ["wayland", "radar", "polar"] },
  { num: "09", id: "glyphs", name: "GLYPHS", sub: "Cryptographic Rain",
    desc: "Cryptographic ASCII character streams and descending digital rain with variable phosphor luminosity and glyph mutators.",
    frame: "60 FPS", cpu: "0.16%", math: "ASCII Matrix Stream",
    tags: ["wayland", "glyphs", "matrix"] },
  { num: "10", id: "gnats", name: "GNATS", sub: "Boid Swarm Ecology",
    desc: "Multi-agent autonomous boid flocking simulation. Agents compute cohesion, separation, and alignment vectors in real-time.",
    frame: "60 FPS", cpu: "0.20%", math: "Reynolds Boids",
    tags: ["wayland", "boids", "swarms"] },
  { num: "11", id: "aurora", name: "AURORA", sub: "Ion Curtain Drift",
    desc: "Slow aurora-borealis curtains over a twinkling starfield. Column-swept exponential falloff with periodic brightening surges.",
    frame: "60 FPS", cpu: "0.12%", math: "Field Falloff",
    tags: ["wayland", "aurora", "field"] },
];
